name: movies
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

#  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dio: ^5.9.0
  dartz: ^0.10.1
  skeletonizer: ^2.1.0+1
  get_it: ^8.2.0
  pretty_dio_logger: ^1.4.0
  injectable: ^2.5.1
  google_fonts: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_gen: ^5.11.0
  flutter_native_splash: ^2.4.6
  alice: ^1.0.0
  alice_dio: ^1.0.7
  blur: ^4.0.2
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  go_router: ^16.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  injectable_generator: ^2.8.1
  flutter_gen_runner: ^5.11.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^3.2.0

# Assets Generator
flutter_gen:
  output: lib/core/generated/

# Splash Screen Generator
flutter_native_splash:
  color: "#0d253f"
  image: assets/native_config/splash_logo.png

# app icon Generator
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/native_config/appicon.webp"
  macos:
    generate: true
  desaturate_tinted_to_grayscale_ios: true
  remove_alpha_ios: true
  background_color: "#0d253f"

flutter:
  uses-material-design: true

  assets:
    - assets/core/